FROM python:3.10.0

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt && \
    rm requirements.txt

COPY ./app /app

ENV PYTHONPATH=/api
WORKDIR /api

EXPOSE 8080 

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]